In [7]:
import gzip
import tensorflow as tf
import numpy as np 

In [2]:
def labelss(filepath):
        with gzip.open(filepath, 'rb') as f:
            labels = []
            
            #Saves variables that arent bytes for labels
            magicNum = (int.from_bytes(f.read(4), "big"))
            noLabels = (int.from_bytes(f.read(4), "big"))
            
            #for loop for range, 60,000/10,000
            for i in range(noLabels):
                #Reads byte at a time and appends to list
                labels.append((int.from_bytes(f.read(1), "big")))
        
        return labels

In [3]:
#append vs extend:  https://stackoverflow.com/questions/252703/difference-between-append-vs-extend-list-methods-in-python

def imagess(filepath):
    with gzip.open(filepath, 'rb') as f:     
        
        #Save variables that are not image bytes
        magicNum = (int.from_bytes(f.read(4), "big"))
        noImages = (int.from_bytes(f.read(4), "big"))
        noRow = (int.from_bytes(f.read(4), "big"))
        noCol = (int.from_bytes(f.read(4), "big"))
                
        images = []
        
        for i in range(noImages):
            row = []
            for k in range(noRow):
                col = []
                for j in range(noCol):
                    col.append(int.from_bytes(f.read(1), "big"))
                #extend used here to add each 28 bytes to 1d array of length [1,2,3,4,5,6]
                #vs append which would create a 2d array [[1,2,3],[4,5,6]]
                row.extend(col)
            images.append(row)     
            
        return images

In [4]:
train_Labels = labelss("C:\\Users\\Damian Curran\\Desktop\\mnist\\train-labels.gz")

In [5]:
train_Images = imagess("C:\\Users\\Damian Curran\\Desktop\\mnist\\train-images.gz")

In [11]:
#np.eye: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.eye.html
#one hot encoding explanation: https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f

#setting depth of one_hot, we have 10 labels
depth = 10

#converts to one_hot vector using numpy
train_Labels_hot = np.eye(depth)[train_Labels_notHot]

#show effects of one_hot
print(train_Labels_notHot[0:5])
print(train_Labels_hot[0:5])

[5 0 4 1 9]
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]
